
<?php
	$title='FOR - Atribuição de atividades';
	include(PATH_TEMPLATE.'header.php');
?>	
			<div id="content">			
				<?php
					include(PATH_TEMPLATE.'sidebar.php');
				?>
				<div id="conteudo">
					<span class="titulo">FOR - Atribuição de atividades</span>
					<?php
						include(PATH_TEMPLATE.'status.php');
					?>
					<form method="POST" action="" id="form-for">
						<?php
						include(PATH_TEMPLATE.'dados-pessoais.php');
							
							if(isset($msg)){
								echo '<div class="ok">FOR enviada com sucesso!</div>';
							}
							if(isset($msg_erro)){
								echo '<div class="msg_erro">Erro no envio!</div>';
							}
							if(isset($validation)) {
								echo '<div class="msg_erro">Problema na validação, verifique se seu javascript está ativado.</div>';
							}
						?>
					
						<div id="for" style="float:left;">
							<table border="1"  style="border:none; width:760px; height:196px; text-align:center;">
								<tr>
									<td rowspan="8" style="padding-right:10px; border:none; font-weight:bold;">M</td>
								</tr>
								<tr>
									<td colspan="2">Aula</td>
									<td style="width:102px; height:25px;">Segunda</td>
									<td style="width:102px; height:25px;">Terça</td>
									<td style="width:102px; height:25px;">Quarta</td>
									<td style="width:102px; height:25px;">Quinta</td>
									<td style="width:102px; height:25px;">Sexta</td>
									<td style="width:102px; height:25px;">Sábado</td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">1</td>
									<td style="width:93px;">7h00 às 7h50</td>
									<td><input type="checkbox" name="1" id="seg1" class="checkHora" <?php if(isset($hour[1])) echo 'checked'; ?>><select name="disc1" id="atvSeg1"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[1]) && $hour[1] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="18" id="ter1" class="checkHora" <?php if(isset($hour[18])) echo 'checked'; ?>><select name="disc18" id="atvTer1"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[18]) && $hour[18] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="34" id="qua1" class="checkHora" <?php if(isset($hour[34])) echo 'checked'; ?>><select name="disc34" id="atvQua1"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[34]) && $hour[34] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="50" id="qui1" class="checkHora" <?php if(isset($hour[50])) echo 'checked'; ?>><select name="disc50" id="atvQui1"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[50]) && $hour[50] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="66" id="sex1" class="checkHora" <?php if(isset($hour[66])) echo 'checked'; ?>><select name="disc66" id="atvSex1"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[66]) && $hour[66] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="82" id="sab1" class="checkHora" <?php if(isset($hour[82])) echo 'checked'; ?>><select name="disc82" id="atvSab1"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[82]) && $hour[82] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">2</td>
									<td>7h50 às 8h40</td>
									<td><input type="checkbox" name="2" id="seg2" class="checkHora" <?php if(isset($hour[2])) echo 'checked'; ?>><select name="disc2" id="atvSeg2"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[2]) && $hour[2] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="19" id="ter2" class="checkHora" <?php if(isset($hour[19])) echo 'checked'; ?>><select name="disc19" id="atvTer2"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[19]) && $hour[19] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="35" id="qua2" class="checkHora" <?php if(isset($hour[35])) echo 'checked'; ?>><select name="disc35" id="atvQua2"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[35]) && $hour[35] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="51" id="qui2" class="checkHora" <?php if(isset($hour[51])) echo 'checked'; ?>><select name="disc51" id="atvQui2"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[51]) && $hour[51] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="67" id="sex2" class="checkHora" <?php if(isset($hour[67])) echo 'checked'; ?>><select name="disc67" id="atvSex2"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[67]) && $hour[67] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="83" id="sab2" class="checkHora" <?php if(isset($hour[83])) echo 'checked'; ?>><select name="disc83" id="atvSab2"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[83]) && $hour[83] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">3</td>
									<td>8h40 às 9h30</td>
									<td><input type="checkbox" name="3" id="seg3" class="checkHora" <?php if(isset($hour[3])) echo 'checked'; ?> ><select name="disc3" id="atvSeg3"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[3]) && $hour[3] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="20" id="ter3" class="checkHora" <?php if(isset($hour[20])) echo 'checked'; ?> ><select name="disc20" id="atvTer3"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[20]) && $hour[20] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="36" id="qua3" class="checkHora" <?php if(isset($hour[36])) echo 'checked'; ?> ><select name="disc36" id="atvQua3"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[36]) && $hour[36] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="52" id="qui3" class="checkHora" <?php if(isset($hour[52])) echo 'checked'; ?> ><select name="disc52" id="atvQui3"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[52]) && $hour[52] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="68" id="sex3" class="checkHora" <?php if(isset($hour[68])) echo 'checked'; ?> ><select name="disc68" id="atvSex3"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[68]) && $hour[68] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="84" id="sab3" class="checkHora" <?php if(isset($hour[84])) echo 'checked'; ?> ><select name="disc84" id="atvSab3"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[84]) && $hour[84] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">4</td>
									<td>9h45 às 10h35</td>
									<td><input type="checkbox" name="4" id="seg4" class="checkHora" <?php if(isset($hour[4])) echo 'checked'; ?>><select name="disc4" id="atvSeg4"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[4]) && $hour[4] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="21" id="ter4" class="checkHora" <?php if(isset($hour[21])) echo 'checked'; ?>><select name="disc21" id="atvTer4"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[21]) && $hour[21] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="37" id="qua4" class="checkHora" <?php if(isset($hour[37])) echo 'checked'; ?>><select name="disc37" id="atvQua4"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[37]) && $hour[37] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="53" id="qui4" class="checkHora" <?php if(isset($hour[53])) echo 'checked'; ?>><select name="disc53" id="atvQui4"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[53]) && $hour[53] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="69" id="sex4" class="checkHora" <?php if(isset($hour[69])) echo 'checked'; ?>><select name="disc69" id="atvSex4"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[69]) && $hour[69] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="85" id="sab4" class="checkHora" <?php if(isset($hour[85])) echo 'checked'; ?>><select name="disc85" id="atvSab4"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[85]) && $hour[85] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">5</td>
									<td>10h35 às 11h25</td>
									<td><input type="checkbox" name="5" id="seg5" class="checkHora" <?php if(isset($hour[5])) echo 'checked'; ?>><select name="disc5" id="atvSeg5"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[5]) && $hour[5] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="22" id="ter5" class="checkHora" <?php if(isset($hour[22])) echo 'checked'; ?>><select name="disc22" id="atvTer5"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[22]) && $hour[22] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="38" id="qua5" class="checkHora" <?php if(isset($hour[38])) echo 'checked'; ?>><select name="disc38" id="atvQua5"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[38]) && $hour[38] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="54" id="qui5" class="checkHora" <?php if(isset($hour[54])) echo 'checked'; ?>><select name="disc54" id="atvQui5"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[54]) && $hour[54] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="70" id="sex5" class="checkHora" <?php if(isset($hour[70])) echo 'checked'; ?>><select name="disc70" id="atvSex5"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[70]) && $hour[70] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="86" id="sab5" class="checkHora" <?php if(isset($hour[86])) echo 'checked'; ?>><select name="disc86" id="atvSab5"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[86]) && $hour[86] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">6</td>
									<td>11h25 às 12h15</td>
									<td><input type="checkbox" name="6" id="seg6" class="checkHora" <?php if(isset($hour[6])) echo 'checked'; ?>><select name="disc6" id="atvSeg6"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[6]) && $hour[6] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="23" id="ter6" class="checkHora" <?php if(isset($hour[23])) echo 'checked'; ?>><select name="disc23" id="atvTer6"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[23]) && $hour[23] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="39" id="qua6" class="checkHora" <?php if(isset($hour[39])) echo 'checked'; ?>><select name="disc39" id="atvQua6"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[39]) && $hour[39] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="55" id="qui6" class="checkHora" <?php if(isset($hour[55])) echo 'checked'; ?>><select name="disc55" id="atvQui6"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[55]) && $hour[55] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="71" id="sex6" class="checkHora" <?php if(isset($hour[71])) echo 'checked'; ?>><select name="disc71" id="atvSex6"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[71]) && $hour[71] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="87" id="sab6" class="checkHora" <?php if(isset($hour[87])) echo 'checked'; ?>><select name="disc87" id="atvSab6"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[87]) && $hour[87] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
							</table>
							<table border="1"  style="border:none; width:760px; height:196px; text-align:center; margin:10px 0;">
								<tr>
									<td rowspan="8" style="padding-right:10px; border:none; font-weight:bold;">V</td>
								</tr>
								<tr>
									<td colspan="2">Aula</td>
									<td style="width:102px; height:25px;">Segunda</td>
									<td style="width:102px; height:25px;">Terça</td>
									<td style="width:102px; height:25px;">Quarta</td>
									<td style="width:102px; height:25px;">Quinta</td>
									<td style="width:102px; height:25px;">Sexta</td>
									<td style="width:102px; height:25px;">Sábado</td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">1</td>
									<td style="width:93px;">13h00 às 14h20</td>
									<td><input type="checkbox" name="7" id="seg7" class="checkHora" <?php if(isset($hour[7])) echo 'checked'; ?>><select name="disc7" id="atvSeg7"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[7]) && $hour[7] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="24" id="ter7" class="checkHora" <?php if(isset($hour[24])) echo 'checked'; ?>><select name="disc24" id="atvTer7"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[24]) && $hour[24] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="40" id="qua7" class="checkHora" <?php if(isset($hour[40])) echo 'checked'; ?>><select name="disc40" id="atvQua7"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[40]) && $hour[40] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="56" id="qui7" class="checkHora" <?php if(isset($hour[56])) echo 'checked'; ?>><select name="disc56" id="atvQui7"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[56]) && $hour[56] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="72" id="sex7" class="checkHora" <?php if(isset($hour[72])) echo 'checked'; ?>><select name="disc72" id="atvSex7"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[72]) && $hour[72] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="88" id="sab7" class="checkHora" <?php if(isset($hour[88])) echo 'checked'; ?>><select name="disc88" id="atvSab7"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[88]) && $hour[88] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">2</td>
									<td>14h20 às 15h10</td>
									<td><input type="checkbox" name="8" id="seg8" class="checkHora" <?php if(isset($hour[8])) echo 'checked'; ?>><select name="disc8" id="atvSeg8"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[8]) && $hour[8] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="25" id="ter8" class="checkHora" <?php if(isset($hour[25])) echo 'checked'; ?>><select name="disc25" id="atvTer8"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[25]) && $hour[25] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="41" id="qua8" class="checkHora" <?php if(isset($hour[41])) echo 'checked'; ?>><select name="disc41" id="atvQua8"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[41]) && $hour[41] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="57" id="qui8" class="checkHora" <?php if(isset($hour[57])) echo 'checked'; ?>><select name="disc57" id="atvQui8"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[57]) && $hour[57] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="73" id="sex8" class="checkHora" <?php if(isset($hour[73])) echo 'checked'; ?>><select name="disc73" id="atvSex8"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[73]) && $hour[73] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="89" id="sab8" class="checkHora" <?php if(isset($hour[89])) echo 'checked'; ?>><select name="disc89" id="atvSab8"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[89]) && $hour[89] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">3</td>
									<td>15h10 às 16h00</td>
									<td><input type="checkbox" name="9" id="seg9" class="checkHora" <?php if(isset($hour[9])) echo 'checked'; ?>><select name="disc9" id="atvSeg9"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[9]) && $hour[9] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="26" id="ter9" class="checkHora" <?php if(isset($hour[26])) echo 'checked'; ?>><select name="disc26" id="atvTer9"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[26]) && $hour[26] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="42" id="qua9" class="checkHora" <?php if(isset($hour[42])) echo 'checked'; ?>><select name="disc42" id="atvQua9"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[42]) && $hour[42] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="58" id="qui9" class="checkHora" <?php if(isset($hour[58])) echo 'checked'; ?>><select name="disc58" id="atvQui9"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[58]) && $hour[58] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="74" id="sex9" class="checkHora" <?php if(isset($hour[74])) echo 'checked'; ?>><select name="disc74" id="atvSex9"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[74]) && $hour[74] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="90" id="sab9" class="checkHora" <?php if(isset($hour[90])) echo 'checked'; ?>><select name="disc90" id="atvSab9"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[90]) && $hour[90] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">4</td>
									<td>16h15 às 17h05</td>
									<td><input type="checkbox" name="10" id="seg10" class="checkHora" <?php if(isset($hour[10])) echo 'checked'; ?>><select name="disc10" id="atvSeg10"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[10]) && $hour[10] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="27" id="ter10" class="checkHora" <?php if(isset($hour[27])) echo 'checked'; ?>><select name="disc27" id="atvTer10"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[27]) && $hour[27] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="43" id="qua10" class="checkHora" <?php if(isset($hour[43])) echo 'checked'; ?>><select name="disc43" id="atvQua10"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[43]) && $hour[43] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="59" id="qui10" class="checkHora" <?php if(isset($hour[59])) echo 'checked'; ?>><select name="disc59" id="atvQui10"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[59]) && $hour[59] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="75" id="sex10" class="checkHora" <?php if(isset($hour[75])) echo 'checked'; ?>><select name="disc75" id="atvSex10"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[75]) && $hour[75] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="91" id="sab10" class="checkHora" <?php if(isset($hour[91])) echo 'checked'; ?>><select name="disc91" id="atvSab10"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[91]) && $hour[91] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">5</td>
									<td>17h05 às 17h55</td>
									<td><input type="checkbox" name="11" id="seg11" class="checkHora" <?php if(isset($hour[11])) echo 'checked'; ?>><select name="disc11" id="atvSeg11"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[11]) && $hour[11] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="28" id="ter11" class="checkHora" <?php if(isset($hour[28])) echo 'checked'; ?>><select name="disc28" id="atvTer11"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[28]) && $hour[28] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="44" id="qua11" class="checkHora" <?php if(isset($hour[44])) echo 'checked'; ?>><select name="disc44" id="atvQua11"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[44]) && $hour[44] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="60" id="qui11" class="checkHora" <?php if(isset($hour[60])) echo 'checked'; ?>><select name="disc60" id="atvQui11"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[60]) && $hour[60] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="76" id="sex11" class="checkHora" <?php if(isset($hour[76])) echo 'checked'; ?>><select name="disc76" id="atvSex11"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[76]) && $hour[76] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="92" id="sab11" class="checkHora" <?php if(isset($hour[92])) echo 'checked'; ?>><select name="disc92" id="atvSab11"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[92]) && $hour[92] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">6</td>
									<td>17h55 às 18h45</td>
									<td><input type="checkbox" name="12" id="seg12" class="checkHora" <?php if(isset($hour[12])) echo 'checked'; ?>><select name="disc12" id="atvSeg12"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[12]) && $hour[12] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="29" id="ter12" class="checkHora" <?php if(isset($hour[29])) echo 'checked'; ?>><select name="disc29" id="atvTer12"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[29]) && $hour[29] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="45" id="qua12" class="checkHora" <?php if(isset($hour[45])) echo 'checked'; ?>><select name="disc45" id="atvQua12"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[45]) && $hour[45] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="61" id="qui12" class="checkHora" <?php if(isset($hour[61])) echo 'checked'; ?>><select name="disc61" id="atvQui12"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[61]) && $hour[61] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="77" id="sex12" class="checkHora" <?php if(isset($hour[77])) echo 'checked'; ?>><select name="disc77" id="atvSex12"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[77]) && $hour[77] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="93" id="sab12" class="checkHora" <?php if(isset($hour[93])) echo 'checked'; ?>><select name="disc93" id="atvSab12"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[93]) && $hour[93] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
							</table>
							<table border="1"  style="border:none; width:760px; height:140px; text-align:center;">
								<tr>
									<td rowspan="8" style="padding-right:10px; border:none; font-weight:bold;">N</td>
								</tr>
								<tr>
									<td colspan="2">Aula</td>
									<td style="width:102px; height:25px;">Segunda</td>
									<td style="width:102px; height:25px;">Terça</td>
									<td style="width:102px; height:25px;">Quarta</td>
									<td style="width:102px; height:25px;">Quinta</td>
									<td style="width:102px; height:25px;">Sexta</td>
									<td style="width:102px; border:none; font-weight:bold; color:#CD2626; text-align:center;" rowspan="5" id="tdHoras">Marque o<br />regime de<br />trabalho.</td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">1</td>
									<td style="width:93px;">19h00 às 19h50</td>
									<td><input type="checkbox" name="13" id="seg13" class="checkHora" <?php if(isset($hour[13])) echo 'checked'; ?>><select name="disc13" id="atvSeg13"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[13]) && $hour[13] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="30" id="ter13" class="checkHora" <?php if(isset($hour[30])) echo 'checked'; ?>><select name="disc30" id="atvTer13"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[30]) && $hour[30] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="46" id="qua13" class="checkHora" <?php if(isset($hour[46])) echo 'checked'; ?>><select name="disc46" id="atvQua13"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[46]) && $hour[46] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="62" id="qui13" class="checkHora" <?php if(isset($hour[62])) echo 'checked'; ?>><select name="disc62" id="atvQui13"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[62]) && $hour[62] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="78" id="sex13" class="checkHora" <?php if(isset($hour[78])) echo 'checked'; ?>><select name="disc78" id="atvSex13"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[78]) && $hour[78] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">2</td>
									<td>19h50 às 20h40</td>
									<td><input type="checkbox" name="14" id="seg14" class="checkHora" <?php if(isset($hour[14])) echo 'checked'; ?>><select name="disc14" id="atvSeg14"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[14]) && $hour[14] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="31" id="ter14" class="checkHora" <?php if(isset($hour[31])) echo 'checked'; ?>><select name="disc31" id="atvTer14"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[31]) && $hour[31] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="47" id="qua14" class="checkHora" <?php if(isset($hour[47])) echo 'checked'; ?>><select name="disc47" id="atvQua14"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[47]) && $hour[47] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="63" id="qui14" class="checkHora" <?php if(isset($hour[63])) echo 'checked'; ?>><select name="disc63" id="atvQui14"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[63]) && $hour[63] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="79" id="sex14" class="checkHora" <?php if(isset($hour[79])) echo 'checked'; ?>><select name="disc79" id="atvSex14"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[79]) && $hour[79] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">3</td>
									<td>20h55 às 21h45</td>
									<td><input type="checkbox" name="15" id="seg15" class="checkHora" <?php if(isset($hour[15])) echo 'checked'; ?>><select name="disc15" id="atvSeg15"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[15]) && $hour[15] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="32" id="ter15" class="checkHora" <?php if(isset($hour[32])) echo 'checked'; ?>><select name="disc32" id="atvTer15"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[32]) && $hour[32] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="48" id="qua15" class="checkHora" <?php if(isset($hour[48])) echo 'checked'; ?>><select name="disc48" id="atvQua15"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[48]) && $hour[48] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="64" id="qui15" class="checkHora" <?php if(isset($hour[64])) echo 'checked'; ?>><select name="disc64" id="atvQui15"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[64]) && $hour[64] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="80" id="sex15" class="checkHora" <?php if(isset($hour[80])) echo 'checked'; ?>><select name="disc80" id="atvSex15"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[80]) && $hour[80] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
								<tr>
									<td style="width:10px; height:25px;">4</td>
									<td>21h45 às 22h35</td>
									<td><input type="checkbox" name="16" id="seg16" class="checkHora" <?php if(isset($hour[16])) echo 'checked'; ?>><select name="disc16" id="atvSeg16"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[16]) && $hour[16] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="33" id="ter16" class="checkHora" <?php if(isset($hour[33])) echo 'checked'; ?>><select name="disc33" id="atvTer16"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[33]) && $hour[33] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="49" id="qua16" class="checkHora" <?php if(isset($hour[49])) echo 'checked'; ?>><select name="disc49" id="atvQua16"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[49]) && $hour[49] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="65" id="qui16" class="checkHora" <?php if(isset($hour[65])) echo 'checked'; ?>><select name="disc65" id="atvQui16"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[65]) && $hour[65] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
									<td><input type="checkbox" name="81" id="sex16" class="checkHora" <?php if(isset($hour[81])) echo 'checked'; ?>><select name="disc81" id="atvSex16"><option value=""></option><?php foreach($disciplinas as $disciplina) : ?><option title="<?php echo $disciplina->getDescricaoExtenso(); ?>" value="<?php echo $disciplina->getId(); ?>" <?php if(isset($hour[81]) && $hour[81] == $disciplina->getId()) echo 'selected'; ?>><?php echo $disciplina->getDescricaoDisciplina(); ?></option><?php endforeach; ?></select></td>
								</tr>
							</table>
							<input type="submit" value="Atribuir" style="margin:10px 0 0 20px;" />
						</div>
					</form>
				</div><!-- fecha conteudo -->
			</div> <!-- fecha content -->
<?php
	include(PATH_TEMPLATE.'footer.php');
?>